// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateServiceVersion(ctx context.Context, arg CreateServiceVersionParams) (ServiceVersion, error)
	DeleteAllServiceVersions(ctx context.Context) error
	DeleteAllServices(ctx context.Context) error
	GetServiceByID(ctx context.Context, id uuid.UUID) (Service, error)
	GetServiceVersionsCount(ctx context.Context, serviceID uuid.UUID) (int64, error)
	GetServicesCount(ctx context.Context) (int64, error)
	GetVersionsByServiceID(ctx context.Context, serviceID uuid.UUID) ([]ServiceVersion, error)
	ListServices(ctx context.Context, arg ListServicesParams) ([]Service, error)
}

var _ Querier = (*Queries)(nil)
